### ISSUE TITLE
Problems with canvas width and height

### ISSUE THREAD

**Issue by mrLoganite** [mayognaise/aframe-draw-shader#2]
Hi,
I have been trying to copy another canvas into the canvas in the draw component.

The source canvas was 640 x 640 and the width and height set on the material properties of the draw component where the same. I was applying it to a square plane and expected the plane to represent the canvas exactly but i discovered the it was clipped. After outputting the values of e.detail.ctx width and height I discovered that they are always 512x512 so I even tried setting all properties on the source canvas and the material properties to 512x512 but the result was still clipped.

I am using 
e.detail.ctx.drawImage(sourceCanvas, 0, 0); 

to copy the canvas

**Comment by mayognaise** [comment]
hi @mrLoganite, the canvas size will automatically convert any size nearest power of two (since the texture size is expected to be a power of two). if you want to use your canvas as 640, try `e.detail.ctx.drawImage(sourceCanvas, 0, 0, sourceCanvas.width, sourceCanvas.height, 0,0,e.detail.ctx.canvas.width,e.detail.ctx.canvas.height);`

**Comment by mrLoganite** [comment]
Worked like a charm!
